apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: brokenwidgets.interview.taikun.cloud
spec:
  group: interview.taikun.cloud
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                message:
                  type: string
  scope: Namespaced
  names:
    plural: brokenwidgets
    singular: brokenwidget
    kind: BrokenWidget
    shortNames:
    - bw
